---
title: "Using git"
author: "Lorenz Walthert"
date: "13. Mai 2016"
output: html_document
---

Some basic commands

```{r, global_options,include=F}
knitr::opts_chunk$set(eval = F) # disable eval
```
## Basic navigation
```{r}
ls # show all elements in directory
cd # change directory
cd .. # up the tree in the directory
pwd # show working directory
```

## Basic git
```{r}
git init 
git status # show the status 
git add text1.txt # add textfile text1 to the stagging area
git add -A # add all unstagged files in working directory to stagging area
git add t* # add all files in the directory that start with t
git commit -m "hi this is a commit" # commiting to current branch
git log  # show the log / history of the git repository
git checkout # dischard changes in stagging area.
```
## Working with branches
```{r}
git branch # show all branches (green star shows current branch)
git branch -v # show all branches (green star shows current branch) and some additonal information

git branch coffee # create a new branch "coffee"
git branch -d coffee # delete the coffee branch
```
## Changing branches 
```{r}
git checkout # dischard changes in stagging area.
git checkout coffee # switch to the coffee branch
git checkout -b old-project-state 0ad5a7a6 # create a new branch called old-roject-state that is the current branch state at commit 0ad5a7a6 


```